In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


In [33]:
df = pd.read_csv(r"C:\Users\Asus\Downloads\autos_mpg.csv")
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model_year  origin                   car_name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [34]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car_name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [35]:
df.shape

(398, 9)

In [36]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car_name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [38]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model_year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [39]:
missing_values =df.isnull().sum()
missing_values

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [40]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [41]:
X = df.iloc[:,:-2].values
y = df.iloc[:,-1].values

In [42]:
print(X)
print("Is X a 2D array?", X.ndim == 2)

[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]
Is X a 2D array? True


In [43]:
print(y)
print("Is y a 2D array?", y.ndim == 2)

['chevrolet chevelle malibu' 'buick skylark 320' 'plymouth satellite'
 'amc rebel sst' 'ford torino' 'ford galaxie 500' 'chevrolet impala'
 'plymouth fury iii' 'pontiac catalina' 'amc ambassador dpl'
 'dodge challenger se' "plymouth 'cuda 340" 'chevrolet monte carlo'
 'buick estate wagon (sw)' 'toyota corona mark ii' 'plymouth duster'
 'amc hornet' 'ford maverick' 'datsun pl510'
 'volkswagen 1131 deluxe sedan' 'peugeot 504' 'audi 100 ls' 'saab 99e'
 'bmw 2002' 'amc gremlin' 'ford f250' 'chevy c20' 'dodge d200' 'hi 1200d'
 'datsun pl510' 'chevrolet vega 2300' 'toyota corona' 'ford pinto'
 'amc gremlin' 'plymouth satellite custom' 'chevrolet chevelle malibu'
 'ford torino 500' 'amc matador' 'chevrolet impala'
 'pontiac catalina brougham' 'ford galaxie 500' 'plymouth fury iii'
 'dodge monaco (sw)' 'ford country squire (sw)' 'pontiac safari (sw)'
 'amc hornet sportabout (sw)' 'chevrolet vega (sw)' 'pontiac firebird'
 'ford mustang' 'mercury capri 2000' 'opel 1900' 'peugeot 304' 'fiat 124b'

In [44]:
X.shape

(398, 7)

In [45]:
X.shape[1]

7

In [46]:
list(range(X.shape[1]))

[0, 1, 2, 3, 4, 5, 6]

In [47]:
# Drop the 'car_name' column as it's not relevant for modeling
df = df.drop(columns=['car_name'])


In [48]:
# Separate features (X) and target variable (y)
X = df.drop(columns=['mpg'])
y = df['mpg']

In [49]:
# Create ColumnTransformer for one-hot encoding
categorical_indices = list(range(X.shape[1]))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_indices)], remainder='passthrough')
X = ct.fit_transform(X)

In [56]:
X 

cylinders  displacement horsepower  weight  acceleration  model_year  \
0            8         307.0        130    3504          12.0          70   
1            8         350.0        165    3693          11.5          70   
2            8         318.0        150    3436          11.0          70   
3            8         304.0        150    3433          12.0          70   
4            8         302.0        140    3449          10.5          70   
..         ...           ...        ...     ...           ...         ...   
393          4         140.0         86    2790          15.6          82   
394          4          97.0         52    2130          24.6          82   
395          4         135.0         84    2295          11.6          82   
396          4         120.0         79    2625          18.6          82   
397          4         119.0         82    2720          19.4          82   

     origin  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
393       1  
394       2  
395       1  
396       1  
397       1  

[398 rows x 7 columns]

In [57]:
# Split the dataset into features (X) and target variable (y)
X = df[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin']]
y = df['mpg']

In [58]:
# Replace non-numeric values (e.g., '?') with NaN
df.replace('?', np.nan, inplace=True)

# Convert all columns to numeric
df = df.apply(pd.to_numeric, errors='coerce')

# Drop rows with NaN values
df.dropna(inplace=True)

In [59]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
#Train model
# Initialize and train the Random Forest Regression model

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [61]:
# Evaluate the model
y_pred_rf = rf_model.predict(X_test)

In [62]:
# Calculate Mean Absolute Error (MAE)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
print("Mean Absolute Error (Random Forest):", mae_rf)

Mean Absolute Error (Random Forest): 1.7185569620253163


In [63]:
# Calculate Mean Squared Error (MSE)
mse_rf = mean_squared_error(y_test, y_pred_rf)
print("Mean Squared Error (Random Forest):", mse_rf)

Mean Squared Error (Random Forest): 5.680200075949368


In [64]:
# Calculate R-squared (R2) score
r2_rf = r2_score(y_test, y_pred_rf)
print("R-squared (R2) Score (Random Forest):", r2_rf)

R-squared (R2) Score (Random Forest): 0.888712085258602


In [65]:
## ORRRR

In [66]:
from sklearn.ensemble import GradientBoostingRegressor

# Initialize and train the Gradient Boosting Regression model
gb_model = GradientBoostingRegressor(random_state=42)
gb_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [67]:
# Evaluate the model
y_pred_gb = gb_model.predict(X_test)

In [68]:
# evaluate model performance

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate Mean Absolute Error (MAE)
mae_gb = mean_absolute_error(y_test, y_pred_gb)
print("Mean Absolute Error (Gradient Boosting):", mae_gb)

Mean Absolute Error (Gradient Boosting): 1.8040615106639244


In [69]:
# Calculate Mean Squared Error (MSE)
mse_gb = mean_squared_error(y_test, y_pred_gb)
print("Mean Squared Error (Gradient Boosting):", mse_gb)

Mean Squared Error (Gradient Boosting): 6.415153366258091


In [70]:
# Calculate R-squared (R2) score
r2_gb = r2_score(y_test, y_pred_gb)
print("R-squared (R2) Score (Gradient Boosting):", r2_gb)

R-squared (R2) Score (Gradient Boosting): 0.8743126947411621
